#!/bin/bash
set -e
cd ${SNAP}/share/games/doom
if [[ $1 == "--snap-launcher" ]]; then
	if [[ $(ls ${SNAP_USER_DATA} | grep .oldargs) != ".oldargs" ]]; then
		touch ${SNAP_USER_DATA}/.oldargs
	fi
	OLDARGS=$(cat ${SNAP_USER_DATA}/.oldargs)
	LAUNCHOPTIONS=$(ls ${SNAP_USER_DATA}/.config/gzdoom | grep .wad | tr -d '\n' | sed 's/.wad/.wad!/g'),$(ls ${SNAP_USER_DATA}/.config/gzdoom | grep .pk3 | tr -d '\n' | sed 's/.pk3/.pk3!/g'),$OLDARGS
	NEWARGS=$(${SNAP}/usr/bin/yad --form --separator="," \
		--field="iwad":CB \
		--field="pwad":CB \
		--field="pk3":CB \
		--field="Skill" \
		--field="Episode" \
		--field="Level" \
		$(echo $LAUNCHOPTIONS | awk -F ',' '{ print $3"!"$1,$4"!"$1,$5"!"$2 }')) 
	if [[ "$NEWARGS" != "$OLDARGS" ]]; then
		echo $NEWARGS > $SNAP_USER_DATA/.oldargs
	fi
	if [[ $(echo $NEWARGS | awk -F ',' '{ print $4 }') != "" ]]; then 
		gzdoom $(echo $NEWARGS | awk -F ',' '{ print "-iwad",$1,"-file",$2,"-file",$3,"-skill",$4,"-warp",$5,$6 }')
	else
		gzdoom $(echo $NEWARGS | awk -F ',' '{ print "-iwad",$1,"-file",$2,"-file",$3 }')
	fi
else
	gzdoom $@

fi
